Memory
MarjorieLV/gb_emu pull request #2
Opened 2018-04-23 17:37 UTC by MarjorieLV

2018-04-23 21:16 UTC, shulrak requested changes

2018-04-23 21:16 UTC, shulrak commented on includes/imemory.hpp
> +    virtual std::array<uint8_t, 0x200000> const & getCartridge() = 0;
Don't use magic numbers. Somewhere add some meaning for 0x200000.

You can either make a separate class for Constants or maybe a next class inside IMemory
Or even inside IMemory. Make sure to have a static const variable.

static const int cartridgeSize = 0x200000;


Instead of using an std::array<uint8_t, 0x20000> everywhere, use a typedef or the 'using' keyword to make an alias and make the code much more readable.
using CartridgeData = std::array<uint_t, 0x200000>;

virtual CartridgeData const & getCartridge() = 0;

you can find a better name :)

2018-04-23 21:16 UTC, shulrak commented on includes/memory.hpp
> +    std::array<uint8_t, 0xffff> const & getReadOnlyMemory();
same no magic numbers

2018-04-23 21:16 UTC, shulrak commented on src/memory.cpp
> +bool isEmpty(std::array<uint8_t, 0xffff> const & rom)
those two function are too similar, you can just use a template function. You can also simplify the code.
here an example : 
```
template<class ARRAY>
bool isEmpty(ARRAY const & memory)
{
   return std::all_of(std::begin(memory), std::end(memory),
                               [](auto elem) { return elem == 0; }); 
   // maybe the auto won't work, you can try ARRAY::value_type
}
```

2018-04-23 21:16 UTC, shulrak commented on test/memory.t.cpp
> +MemoryTest::MemoryTest()
move this function inside the class it self, it's contain the Fixture so that when we are reading we don't get any noise

2018-04-23 21:16 UTC, shulrak commented on test/memory.t.cpp
> +    std::array<uint8_t, 0x4000> _bank0;
use aliase here too,
Also bank0 is never used is that normal ?

2018-04-24 15:24 UTC, Sgregory42 requested changes

2018-04-24 15:24 UTC, Sgregory42 commented on includes/memory.hpp
> +    IMemory::CartridgeData const & getCartridge();
seems like you don't need IMemory here :)

2018-04-24 15:24 UTC, Sgregory42 commented on test/memory.t.cpp
> +        EXPECT_EQ(_bank0[i], rom[i]);
instead of having your if 
you can do this : 
```
EXPECT_EQ(_bank0[i], rom[i]) << "i = " << i;
```
This will print additional info when it fails

2018-04-24 16:01 UTC, Sgregory42 approved these changes

2018-04-24 16:02 UTC, merged