Marjorie lv/instructions map
MarjorieLV/gb_emu pull request #5
Opened 2018-06-19 17:15 UTC by MarjorieLV

2018-06-24 18:35 UTC, shulrak approved these changes

2018-10-17 10:29 UTC, Sgregory42 requested changes

2018-10-17 10:29 UTC, Sgregory42 commented on src/memory.cpp
> +    return _readOnlyMemory[adress];
is this safe ? what if adress is out of bound ?

2018-10-17 10:29 UTC, Sgregory42 commented on src/memory.cpp
> +    return bitset.test((int)flag);
1. don't use c-style casting. use static_cast<int>()
2. don't cast everywhere, you can create at the beginning of the function :
const int flagValue = static_cast<int>(flag); 
and use this

2018-10-18 20:21 UTC, closed without merging